import Head from 'next/head'
import Link from "next/link";

export default function Home() {

    return (
        <>
            <Head>
                <title>Camurria</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <div id="products" >
                    <Link className="text-3xl" href={"/products/"}> Vai alla sezione Prodotti </Link>
                </div>
                <div id="accounts">
                    <Link href={"/profiles/"}> Vai alla sezione Profili </Link>
                </div>
            </main>
        </>
    )
}
