global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['localhost:9090']
    - job_name: 'apps'
      metrics_path: '/actuator/prometheus'
      static_configs:
      - targets: ['host.docker.internal:8081']
    - job_name: 'keycloak'
      metrics_path: '/metrics'
      static_configs:
      - targets: ['host.docker.internal:8080']
